site_name: Lime Bootstrap
pages:
- 'Home': '1. Introduction.md'
- 'Getting started': '2. Getting started.md'
- 'Included components': '3. Included components.md'
- 'Bindnings & filters': '4. Bindings and filters.md'
- 'Data sources': '5. DataSources.md'
- 'Custom components Apps': '6. Custom components.md'
- 'Advanced': '7. Advanced.md'
theme: readthedocs
repo_url: https://github.com/Lundalogik/LimeBootstrap
site_description: LimeBootstrap dokumentation
site_author: Lime Technologies AB
docs_dir: docs
dev_addr: localhost:3002
theme:
  name: 'material'
markdown_extensions:
- codehilite
- admonition
extra_css:
  - 'styles/custom.css'
