site_name: LimeBootstrap
pages:
- 'Home': 'index.md'
- 'Philosophy': 'philosophy.md'
- 'Basic Usage': 'basicUsage.md'
- 'Advanced': 'advanced.md'
- 'Building Apps': 'buildingApps.md'
- 'Changelog': 'changelog.md'
- 'Technical Platform': 'technicalPlatform.md'
- 'Python - Installation and configuration': 'python.md'
theme: readthedocs
repo_url: https://github.com/Lundalogik/LimeBootstrap
site_description: LimeBootstrap dokumentation
site_author: Lundalogik AB
docs_dir: docs
dev_addr: 127.0.0.1:8000